name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or master, depending on your default branch

# Add permissions block
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build static files
        run: |
          mkdir -p dist
          cp -r src/static dist/
          cp -r src/templates dist/
          cp src/amazon_price_comparison.py dist/
          cp src/main.py dist/
          cp src/templates/index.html dist/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
